# Date: 2024-6-13
# Author: Generated by GoCodeo.


import unittest 

from love import flash_message 

class Testflash_message(unittest.TestCase):

	    def test_negative_interval(self):
	        with self.assertRaises(ValueError):
	            flash_message('Michelle', interval=-1.5) 


