# Date: 2024-6-13
# Author: Generated by GoCodeo.


import unittest 

from love import flash_message 

class Testflash_message(unittest.TestCase):

	    def test_empty_name(self):
	        expected_output = 'I love you, !'
	        with unittest.mock.patch('builtins.print') as mock_print:
	            flash_message('')
	            mock_print.assert_called_with(expected_output) 


