# Date: 2024-6-13
# Author: Generated by GoCodeo.


import unittest 

from love import flash_message 

class Testflash_message(unittest.TestCase):

	    def test_flash_message_default(self):
	        flash_message('Michelle') 


